sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

before_install:
  - gem update --system
  - gem install bundler

cache: bundler

script: bundle exec middleman build

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master

env:
  global:
    secure: hWAhEEuObNF7ugoosPlsZbcAFO57BRsrCt1P4M7ir73KKL4dHzuqHVix8PGN3ol4sWQp+kCuZmGGhceF8oxgF6XCVHlIiNYdfwG4GaxigjGCdXsdnrt9Sf5quvvsHXa2bgU0e9TE2HqlWz7jQsuMJ3AQK0MnAAKTn2cNJUlYGnUzDsYmn5PuYqKLrXPRmVr+vpPNDmJ2PeCy97+2UHmtEvVPX/7ABtiwvwo9UakpvOQJ7Xr/miSsd62Y/GCt/btL1l+zWj+7N8EEnAi+MYUYud2ECnbGN2EBRjcwPeww7BxTKJSVbjxtHDzD1d7N1UhIPBbTCC/BLlwciAaZ6+NmDjTfrKEDLP4ITfo+FfriF7f8WLFkogp1CWMyOGwC3A1E0JaYlVb3BxvMwkHUWPsVUV+iqiJYcA47eCqGuSXZXbVz7GVO6Mw/+KyKmYh9cTinW5aqQaeuukpIYLGttFoGy3H/BEJkv/sUcuJwfZ6EtnrpKBr0MEik4rbPoOz7AyoBf1QFUKa4KC22Aog1LQDj0NF6aPrqaE6n+EvU2pRZ8Ee6kM67HAsjbWM0zUb/pISlPbdTXs5eJcNySsT07+SklLWt8C/eJQuwTMkcN/r427tlfU3Y3mZ3bFHa9AZjLxxzxcplJahLsJF9FUjlKyxonTsUe7apU+hpzaWxMK584EI=
fe
